### ISSUE TITLE
AssertionError: Not OLE file

### ISSUE THREAD

**Issue by liubean** [nolze/msoffcrypto-tool#14]
PS C:\> msoffcrypto-tool -p 123456  .\test.xlsx
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\Scripts\msoffcrypto-tool-script.py", line 11, in <module>
    load_entry_point('msoffcrypto-tool==4.6.1', 'console_scripts', 'msoffcrypto-tool')()
  File "d:\program files\anaconda3\lib\site-packages\msoffcrypto_tool-4.6.1-py3.6.egg\msoffcrypto\__main__.py", line 58, in main
AssertionError: Not OLE file

**Comment by nolze** [comment]
Thank you for reporting. There are several possibilities:

* `test.xlsx` is not encrypted. (You may try `msoffcrypto-tool -t .\test.xlsx`)
* `test.xlsx` is corrupted.
* If `test.xlsx` is valid and encrypted, the error has something to do with [olefile](https://github.com/decalage2/olefile) library. In that case we could open an issue there if you are OK to supply the file for investigation.

**Comment by nolze** [comment]
Close inactive issue. Please reopen if there is any update.
