### ISSUE TITLE
Bug in decrypting '97 office docs

### ISSUE THREAD

**Issue by deeso** [nolze/msoffcrypto-tool#17]
Unable to decrypt an office '97 document.  The decryption fails here: https://github.com/nolze/msoffcrypto-tool/blob/master/msoffcrypto/format/doc97.py#L392

Document file is attached to the email found here: https://www.malware-traffic-analysis.net/2018/08/21/index2.html

Please contact me with questions, and I can provide the raw file for your convenience.

**Comment by nolze** [comment]
See also @deeso's comment in #18.
