### ISSUE TITLE
AssertionError in load_key

### ISSUE THREAD

**Issue by mlindhout** [nolze/msoffcrypto-tool#19]
I have an encrypted xlsx file, don't know which format and trying to decrypt it with:

file.load_key(password=args.password)

 gives me:

..../msoffcrypto/format/ooxml.py", line 116, in load_key
raise AssertionError()

Key is not verified

**Comment by nolze** [comment]
Usually it means that a wrong password is provided. (I'll fix the confusing AssertionError message.)

I see no evident bug in the implementation. If you can decrypt the file with MS Excel or LibreOffice though, possibly it would be that 

* the format of the file is wrongly recognized by msoffcrypto-tool, or
* Key verification data is corrupted but ignored by MS Excel.

Please make sure your password is correct, or I'll investigate the file if you could provide it with or without password.

**Comment by nolze** [comment]
Closing inactive issue. Please reopen if there is any update. (The error message is slightly improved by #20)
