### ISSUE TITLE
IOError: not an OLE2 structured storage file

### ISSUE THREAD

**Issue by pruppert** [nolze/msoffcrypto-tool#23]
Any idea what this error means and how to work fix it?

Generated from the following code:

```
import msoffcrypto

file = msoffcrypto.OfficeFile(open("/Users/path/to/my/file.docx", "rb"))
file.load_key(password="password")
file.decrypt(open("/Users/path/to/my/file.docx", "wb"))
```

**Comment by pruppert** [comment]
More info. Command line tool says the docx is encrypted. Trying to decrypt via command line results in:

`Exception: Not OLE file`

**Comment by pruppert** [comment]
More info. The command line successfully decrypts despite giving the:

`Exception: Not OLE file`

**Comment by pruppert** [comment]
Update. While the command line does decrypt, it deletes all contents of the docx.

**Comment by nolze** [comment]
Hi, as I could not reproduce the errors with the files in [``/tests``](https://github.com/nolze/msoffcrypto-tool/tree/master/tests) and see no obvious cause, there may be something special with your file.
If you can restore the original file, it's worth another try to run the latest version (4.6.4)  with the verbose (`-v`) option to see the detail; or I'll investigate the file if you could provide it with or without password.

**Comment by nolze** [comment]
Closing inactive issue. Please reopen if there is any update.
