### ISSUE TITLE
Timeline for support for PPT

### ISSUE THREAD

**Issue by stephenthornhill** [nolze/msoffcrypto-tool#24]
Hi,

This software is great and has proven very useful to us to be able to convert encrypted office docs to pdf files.

I was just wondering if there was any plans to support MS-PPT (PowerPoint 2002, 2003, 2004) files?  I know these are not currently supported so this isn't a bug as such.  Just wondering about future plans?

We appreciate your help and effort on this project.

Thanks very much,

   Stephen

**Comment by nolze** [comment]
Thanks!
I just thought there is little demand for it. I carried out partial support for MS-PPT by #26 . It should work for basic PowerPoint 97+ presentations without photos.
While there is no fixed schedule for updates, I usually maintain this entire project once a month.
I welcome any pull requests as always.

**Comment by christian-intra2net** [comment]
So, all I would have had to do was ask?! That is great! Thanks a lot.
I am currently creating a small wrapper around msoffcrypto to include it in oletools. So I can now remove the extra tests for "if this is ppt, then raise error".

**Comment by stephen-thornhill-ms** [comment]
Wow!  That's amazing!  Thank you so much!

    Stephen
