### ISSUE TITLE
File decrypt error

### ISSUE THREAD

**Issue by adityaaggarwal1992** [nolze/msoffcrypto-tool#32]
Office 16 test case
Tried it via a script and it throws the following exception:
```

totalSize = unpack('<I', ibuf.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes
```

**Comment by nolze** [comment]
Thank you for reporting!

There's no known issue for this, but it would be helpful to ensure that the file is seeked to the very beginning (``file.seek(0)``) before you load it with `msoffcrypto.OfficeFile(file)`.

I'll check it if you could you attach the equivalent script and document (please make sure to remove secrets.) I'd appreciate a fix PR too.

**Comment by nolze** [comment]
Closing inactive issue. Please reopen if there is any update.
