### ISSUE TITLE
Office 95

### ISSUE THREAD

**Issue by bartengine27** [nolze/msoffcrypto-tool#34]
Hi,

  Any idea how Office 95 word documents should be decrypted?

Thanks,
Bart

**Comment by nolze** [comment]
Hi Bart, Word 95 decryption is not yet supported by msoffcrypto-tool.

For now, you could have a look at [wvDecrypt](http://www.skynet.ie/~caolan/Packages/wvDecrypt.html) (or [wvWare](http://wvware.sourceforge.net/) a part of which is wvDecrypt). I suppose LibreOffice supports Word 95 decryption as well.

**Comment by nolze** [comment]
Closing inactive issue. Please reopen if there is any update.
