### ISSUE TITLE
UnboundLocalError: local variable 'obuf' referenced before assignment

### ISSUE THREAD

**Issue by lixiang2017** [nolze/msoffcrypto-tool#42]
when I test according to README.md, the error was raised.
the code in ipython is :
```
In [1]: import msoffcrypto

In [2]: file = msoffcrypto.OfficeFile(open("blnr_cyjl.odt", "rb"))

In [3]: file.load_key(password="#rx@q&ft47*1p3zkeg")

In [4]: file.decrypt(open("blnr_cyjl.odt", "wb"))
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-4-f463435a37e0> in <module>()
----> 1 file.decrypt(open("blnr_cyjl.odt", "wb"))

/Library/Python/2.7/site-packages/msoffcrypto/format/ooxml.pyc in decrypt(self, ofile)
    150
    151         # If the file is successfully decrypted, there must be a valid OOXML file, i.e. a valid zip file
--> 152         if not zipfile.is_zipfile(io.BytesIO(obuf)):
    153             raise Exception("The file could not be decrypted with this password")
    154

UnboundLocalError: local variable 'obuf' referenced before assignment

In [5]:
```

**Comment by nolze** [comment]
Thanks for reporting!
I guess that your file `blnr_cyjl.odt` is not a MS Office fie (.doc, .docx, .ppt, .pptx and such) but a OpenDocument file (.odt, .odp etc.), which is not supproted by the library.

[The spec is publicly available](https://en.wikipedia.org/wiki/OpenDocument_technical_specification#Encryption) and hopefully we will support it as a part of a larger project in future.

**Comment by priya-blitz** [comment]
import msoffcrypto
       file = msoffcrypto.OfficeFile(open('file.xlsx', 'rb'))
        file.load_key(password='hjadsfsadjkf')
        file.decrypt(open('file.xlsx', 'wb'))
------------------------------------------------------------
Traceback (most recent call last):

python3.7/site-packages/flask/app.py", line 2463, in __call__
if not zipfile.is_zipfile(io.BytesIO(obuf)):
UnboundLocalError: local variable 'obuf' referenced before assignment

**Comment by nolze** [comment]
Hi priya-blitz, you can't overwrite the file in decryption (`file.xlsx` here.)
Try writing to a new file and replace the decrypted one with it if necessary.
