### ISSUE TITLE
How to check if file is encrypted?

### ISSUE THREAD

**Issue by vanniekerkalex** [nolze/msoffcrypto-tool#43]
Hi,

I would like to check if an office file is encrypted by using the Msoffcrypto-tool without using the CLI. Meaning, using it as a package, is this possible?

I can't seem to find any documentation on functionality / methods other than with the CLI?

Something like this:

```
inputPath = "tests/inputs/plain.doc"
file = msoffcrypto.OfficeFile(open(inputPath, "rb"))
file_encr = msoffcrypto.file.is_encrypted()
print(file_encr)
```

Thanks!

**Comment by nolze** [comment]
You're almost right; as `file` is instantiated as an office file object, just use `file.is_encrypted()` instead of `msoffcrypto.file.is_encrypted()`:

```
inputPath = "tests/inputs/plain.doc"
file = msoffcrypto.OfficeFile(open(inputPath, "rb"))
file_encr = file.is_encrypted()
print(file_encr)  # should print True or False, but may print 1 or 0 at the moment (to be fixed)
```

**Comment by vanniekerkalex** [comment]
Hi @nolze - that's perfect... all I needed and it works. Thank you very much! :)
