### ISSUE TITLE
Improvement: Better Exception Type

### ISSUE THREAD

**Issue by cal97g** [nolze/msoffcrypto-tool#50]
It would be better to raise a more specific exception than `Exception` - in fact I believe `Exception` should not be raised and it's real use is as a catch all for try/catch.

By using something more appropriate, eg ValueError(?), or implementing our own error types we can catch errors better.

excuse the naming but an example is below:
```
MsOffCryptoBaseException(Exception):
  pass

IncorrectPasswordException(MsOffCryptoBaseException):
  pass
``` 

Currently I need to inspect the exception message to determine the cause of failure. I believe raising a specific error is a much nicer pattern and will not break compatibility with previous code as catch Exception will still catch this.

**Comment by decalage2** [comment]
I would also suggest `UnrecognizedFormatError` instead of `Exception("Unrecognized file format")`.
