### ISSUE TITLE
Encrypt files?

### ISSUE THREAD

**Issue by cristianocca** [nolze/msoffcrypto-tool#51]
Hello,

What would it take for the library to also support encryption of docx files? :)

**Comment by nolze** [comment]
Hi, to support encryption we need to implement the very reverse of some functions in [`/format/*`](https://github.com/nolze/msoffcrypto-tool/tree/master/msoffcrypto/format) and [`/method/*`](https://github.com/nolze/msoffcrypto-tool/tree/master/msoffcrypto/method). I guess that it is not so difficult in the case of OOXML documents (including .docx), but there must be some pitfalls in other cases.

[I plan to support encryption in future](https://github.com/nolze/msoffcrypto-tool#todo), but the priority is low reflecting the low demand for it compared to decryption.

**Comment by cristianocca** [comment]
I wouldn't mind encryption being available only for OOXML files :)

**Comment by thnisweden** [comment]
I would also greatly appreciate to have both decryption and encryption possibilities available in one package. OOXML files only are also fine for me.

**Comment by DenizUgur** [comment]
I would also like to see the encryption on Excel files. If you need support I can help.

**Comment by lightning003** [comment]
Is anyone working on this? I have checked out mentioned [repo ](https://github.com/herumi/msoffice) and one of the node library [xls-populate](https://github.com/dtjohnson/xlsx-populate/blob/7480a02575c9140c0e7995623ea192c88c1886d3/lib/Encryptor.js) 
 but I am not getting it that much. Any insights or specific things I can follow to implement it?

**Comment by DenizUgur** [comment]
Well, in my project I was using Docker so I compiled the repo I mentioned and called it via child_process on python. Maybe you could do something similar? If you need a reference I can create a gist.

**Comment by palharishchandra** [comment]
Is there any python module to encrypt file with password ?

**Comment by icodexys** [comment]
> Is there any python module to encrypt files with passwords?

there is a couple I guest, like   ' from cryptography.fernet import Fernet '.....but you can check my code without using modules, just the XOR (^) operator  and a password,...the encryption would be strong if you use a complex password (numbers, uppercases, special symbols, etc),  here: https://github.com/icodexys/S1mple-3ncryt1on/blob/main/Encrypt_files.py

**Comment by stephane-rouleau** [comment]
I created a pull request to provide encryption support on OOXML files.

**Comment by nolze** [comment]
I'm pleased to share that msoffcrypto-tool now supports encryption for OOXML documents (.docx, .xlsx, .pptx), starting from version 5.3.0. This enhancement is made possible by the valuable contribution of @stephane-rouleau in PR #86.
