### ISSUE TITLE
The code on PyPI doesn't match the code in the repository

### ISSUE THREAD

**Issue by mnestis** [nolze/msoffcrypto-tool#52]
Pulling the code from PyPI gives different code to that in the repository.

As an example, the file `msoffcrypto/format/ooxml.py` has a class (`OOXMLFile`) with a method `load_key`. From the code in this repository, I would expect that method to accept a keyword argument `verify_password`. The version of the file available on PyPI as version 4.10.2 (and 4.10.1, but that's all I've checked) does not.

Similarly, the `decrypt` method of the same class is missing its `verify_integrity` argument.

**Comment by nolze** [comment]
Thank you for the comment. Those features were added after the 4.10.2 release and we haven't pushed them to PyPI yet.
If necessary, you can install the latest master with `pip install git+https://github.com/nolze/msoffcrypto-tool`.
