### ISSUE TITLE
UnboundLocalError: local variable 'obuf' referenced before assignment

### ISSUE THREAD

**Issue by palharishchandra** [nolze/msoffcrypto-tool#62]
Traceback (most recent call last):
  File "c:/Project/Human_Machine/old_task/word_activity.py", line 13, in <module>
    file.decrypt(f)
  File "C:\Users\hari\AppData\Local\Programs\Python\Python36\lib\site-packages\msoffcrypto\format\ooxml.py", line 198, in decrypt
    if not zipfile.is_zipfile(io.BytesIO(obuf)):
UnboundLocalError: local variable 'obuf' referenced before assignment

`
import msoffcrypto

encrypted = open(
    'C:\\Project\\Human_Machine\\old_task\\word_text.docx',
    "rb")
file = msoffcrypto.OfficeFile(encrypted)

file.load_key(password="Passw0rd")  # Use password

with open("decrypted.docx", "wb") as f:
    file.decrypt(f)

print("encypt completed")
encrypted.close()
`

After I run the above code one files get created of 0kb.

**Comment by palharishchandra** [comment]
Found the issue, file was not password protected.

**Comment by nolze** [comment]
Improved error handling in <https://github.com/nolze/msoffcrypto-tool/commit/8b78a984433631f2f2aec55cc67359e5baf49aed>. Thanks!
