### ISSUE TITLE
if I input an .xls file, decrypted file is .xlsx format?

### ISSUE THREAD

**Issue by sonicwong** [nolze/msoffcrypto-tool#64]
if I input an .xls file, decrypted file is .xlsx format? or I can select .xls / .xlsx?

**Comment by nolze** [comment]
In principle, it's .xls for .xls, and .xlsx for .xlsx. Note that even if the file extension is .xls, it may actually be .xlsx (or vice versa). MS Word will probably open it regardless of that.
