### ISSUE TITLE
Module doesnt work when compiled into a binary

### ISSUE THREAD

**Issue by NatSavBS** [nolze/msoffcrypto-tool#65]
On line 7 of __init__.py, the module version is retrieved.
```python
__version__ = pkg_resources.get_distribution("msoffcrypto-tool").version
```

This does not work when the module is used as a part of a compiled program as msoffcrypto is the name of the actual import and is thus what is compiled.

I have worked around this temporarily by modifying this line to just set a value. 
```python
__version__ = 1
```

**Steps to recreate**
Attempt to compile a program using msoffcrypto (I used auto-py-to-exe)
Run the created executable from a terminal.

**Comment by nolze** [comment]
Thank you for the report!
In fact, auto-py-to-exe uses pyinstaller inside, and a fix has been made for your point: https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/139
This fix has not been released yet, however, so you will have to wait for the next release or incorporate the latest master yourself in some way.

**Comment by NatSavBS** [comment]
Thanks for the reply, I managed to got it working eventually. Good to hear that it is being looked into.
