### ISSUE TITLE
Decrypt XLS File

### ISSUE THREAD

**Issue by firstpp** [nolze/msoffcrypto-tool#69]
I can't seem to get this library to work with my XLS File.

```import msoffcrypto
import io
import pandas as pd

PATH = src_dir+"/"+files[0]
print(PATH)
decrypted = io.BytesIO()

with open(PATH, "rb") as f:
    file = msoffcrypto.OfficeFile(f)
    print(file.is_encrypted())
    file.load_key(password="Password")  # Use password
    file.decrypt(decrypted)

df = pd.read_excel(decrypted)
print(df)
```
I'm getting InvalidKeyError: Failed to verify password. Is this due to XLS being in experimental stage?

**Comment by nolze** [comment]
> ```
>     file.load_key(password="Password")  # Use password
> ```

Have you filled the correct password here for your XLS file?
If it doesn't work even with the correct one, I'll check it if you could you attach the file in question (please make sure to remove secrets.)

**Comment by firstpp** [comment]
> file.load_key(password="Password")

I used this to post because the password contains my company name. May I email you the file with the password?

**Comment by nolze** [comment]
Thanks, but can you paste here the entire error message which includes the lines caused it (without secrets) before that? It might be enough.

**Comment by firstpp** [comment]
Here is the entire error message:

```
InvalidKeyError: Failed to verify password
---------------------------------------------------------------------------
InvalidKeyError                           Traceback (most recent call last)
<command-3917825333057654> in <module>
     10     file = msoffcrypto.OfficeFile(f)
     11     print(file.is_encrypted())
---> 12     file.load_key(password="Password")  # Use password
     13     file.decrypt(decrypted)
     14 

/databricks/python/lib/python3.8/site-packages/msoffcrypto/format/xls97.py in load_key(self, password)
    521                 self.salt = info["salt"]
    522             else:
--> 523                 raise exceptions.InvalidKeyError("Failed to verify password")
    524         elif vMajor in [0x0002, 0x0003, 0x0004] and vMinor == 0x0002:  # RC4 CryptoAPI
    525             info = _parse_header_RC4CryptoAPI(encryptionInfo)
```

**Comment by nolze** [comment]
As far as I can tell, it means that the password cannot be verified (=wrong password.)
If you can open the file in MS Excel with the same password, there is something wrong with this library.
I cannot recommend it at all, but if you are really sure and happy to share the file, send the file to the email address on my profile.

**Comment by nolze** [comment]
Thank you for the email! I found that your file falls into the following case, please chek them out:

* https://twitter.com/decalage2/status/1196905331668013057
* https://stackoverflow.com/questions/68256650/load-xls-files-with-pandas-is-failed

**Comment by firstpp** [comment]
Wow, this is such an obscure issue. Thank you so much for your help!
