### ISSUE TITLE
xls97.decrypt - Missing type attribute

### ISSUE THREAD

**Issue by wit0k** [nolze/msoffcrypto-tool#70]
Hello,

The file .../site-packages/msoffcrypto/format/xls97.py:

class Xls97File has a problem in "decrypt" function.

Sometimes it fails on "if self.type ==" when self has NO "type" attribute...

A nasty workaround is to try it within Try catch, before real evaluation and return if it fails, but it would be nice to prevent it in code which populates the type...

Thx

**Comment by nolze** [comment]
Thank you for reporting!
Now `msoffcrypto.exceptions.DecryptionError` is raised for that (in `master`, not yet released.) (https://github.com/nolze/msoffcrypto-tool/commit/e6f1a3420b32b9d39601e3508fc5e39b57d6d885#diff-d56dcacb58a9b50a4ea6d4e6dda0e5e4907bc8071795b15ca9f9472a93035158R589)
Note that msoffcrypto supports only RC4 and RC4 CryptoAPI encryptions. Let me know if you're working on something else.

**Comment by wit0k** [comment]
Thank you.

**Comment by nolze** [comment]
Released in [v5.0.0](https://github.com/nolze/msoffcrypto-tool/blob/master/CHANGELOG.md#500--2022-01-20).
