### ISSUE TITLE
TypeError: Xls97File.load_key() got an unexpected keyword argument 'verify_password'

### ISSUE THREAD

**Issue by yslion** [nolze/msoffcrypto-tool#73]
file.load_key(password=str(pwd), verify_password=True) 

I success decrypt  one xls file  ,    but when try another xls file  ,  raise this  error .   

because  of  same  ilename extension  different format ?

how to fix it    thanks

**Comment by nolze** [comment]
The `verify_password` argument is available only for xlsx and not for xls.
You can check if a file is an xlsx or not beforehand, for example:

```python
if file.format == "ooxml" and file.type in ["standard", "agile"]:
    file.load_key(password=PASSWORD, verify_password=True)
else:
    file.load_key(password=PASSWORD)
```
