### ISSUE TITLE
Unprotected file raising FileFormatError instead of returning False when checked with is_encrypted()

### ISSUE THREAD

**Issue by it-sanwa-ei** [nolze/msoffcrypto-tool#74]
`import msoffcrypto`

`protected = './protected.xlsx'`
`unprotected = './unprotected.xlsx'`
`password = '12345'`

`file = open(protected, 'rb')`
`ms_file = msoffcrypto.OfficeFile(file).is_encrypted()`
`print(ms_file)`

This return 

> True

, but when I try

`file = open(unprotected, 'rb')`
`ms_file = msoffcrypto.OfficeFile(file).is_encrypted()`
`print(ms_file)`

This give me 

> FileFormatError: Unencrypted document or unsupported file format

 instead of False

**Comment by nolze** [comment]
Fixed in d0383c8 and released v5.1.0. Thank you for reporting!
