### ISSUE TITLE
Issue with package distribution metadata set for package version. 

### ISSUE THREAD

**Issue by atomey** [nolze/msoffcrypto-tool#77]
I'm having an issue with using this package in a virtual environment in Python 3.11. I noticed the pkg_resources call to pull the versioning when msoffcrypto-tool runs the __init__.py is wrong.

It seems this should now be done using the importlib_metadata, which is included since Python 3.8. I've updated the module locally to import with this method and now do not get any distribution errors:

```
try:
    import importlib_metadata
except ImportError:
    import importlib.metadata as importlib_metadata

__version__ = importlib_metadata.version("msoffcrypto-tool")
```

Confirmed here https://setuptools.pypa.io/en/latest/pkg_resources.html, pkg_resources is deprecated.

**Comment by nolze** [comment]
Fixed in v5.1.0. Thank you for reporting!
