### ISSUE TITLE
Is there any plan to support decryption of XORObfuscation algorithm?

### ISSUE THREAD

**Issue by zurmokeeper** [nolze/msoffcrypto-tool#79]
Is there any plan to support decryption of XORObfuscation algorithm?

**Comment by nolze** [comment]
I have a plan, but no specific timeline.

**Comment by zurmokeeper** [comment]
@nolze Great, actually that's what I wanted. thank you very much

**Comment by zurmokeeper** [comment]
@nolze There is another question I would like to ask, the following logic such as the decryption of xls:

         if num == recordNameNum["FilePass"]:
                plain_buf += [0, 0] + list(pack("<H", size)) + [0] * size
                encrypted_buf.write(b"\x00" * (4 + size))

        for c in plain_buf:
            if c == -1:
                dec.seek(1, 1)
            else:
                dec.write(bytearray([c]))
May I ask where it is mentioned, I have been looking for documents for a long time, but I can't find any specific encrypted content and decrypted content?

**Comment by nolze** [comment]
I'm sorry, but I can't recall the details right now. (The last commit was last year.)
I usually refer to the official specs and sometimes to other resources listed in https://github.com/nolze/msoffcrypto-tool/#resources.
