### ISSUE TITLE
DeprecationWarning from cryptography library 

### ISSUE THREAD

**Issue by dennn11** [nolze/msoffcrypto-tool#92]
![Screenshot 2024-07-30 074345](https://github.com/user-attachments/assets/6e5a7cc4-f79f-4208-8e5d-97808b9e0346)

A deprecation warning coming from the cryptography library when I try to open xls file

**Comment by nolze** [comment]
Fixed in v5.3.2. Thank you for reporting!

- https://github.com/nolze/msoffcrypto-tool/commit/6b5674ffba2387d5ff989836ff1c17fc96bcd432
